# Select base image
FROM nvidia/cuda:11.3.0-cudnn8-devel-ubuntu18.04

# need a ssh public key to access this container.
ARG SSH_KEY_PATH

# before start, remember that you are root in this container, not a sudoer.
# Most of the case, sudo is not installed in base image.

# install commonly used apt packages
RUN apt update && apt install build-essential git zsh wget curl ssh tmux python3-distutils python3-dev libgl1-mesa-glx -y && systemctl enable ssh.service

# install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py

COPY copy/ /root/
RUN chmod 755 /root/run.sh

# install requirements
RUN python3 -m pip install -r /root/requirements.txt

# copy ssh public key 
RUN mkdir -p /root/.ssh
COPY $SSH_KEY_PATH /root/.ssh/authorized_keys

# expose ssh port
EXPOSE 22